language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
- java -jar selenium-server-standalone-2.28.0.jar > /dev/null &
- sleep 5
script:
- npm run-script selenium
addons:
  firefox: '17.0'
deploy:
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: NWiOpw3fFSo6zzB1t3DWwUNqpT/1cGyHYCFnFq2yxaZ//2YRc7ZJmj94PF7VahrWqHZwHZT69bbp9DPWyRjn4gSNMtjF7Cq/s11RPExazFmpyulfRSoUjxpaWgU1DKpaCDJmJHe9BnjRFBS/oAG31sDj/v/dElY9T+rtATXRpRM=
  app: goabonga-welcome
  on:
    repo: goabonga/master
