language: node_js

node_js:
  - '0.11'
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
  - java -jar selenium-server-standalone-2.28.0.jar > /dev/null &
